sudo: false

dist: xenial

language: python

notifications:
  slack:
    secure: TAdglasemUBfDQ9KkpK9ovBUYSBabxKGTIgHejuV4QJzEYH6YMrL1ygZlHAaSLl8jy63oQ4SlPEIRYhs61AUhHy2dJ3IqT4EzKs9SSqAFR5l1iHLxlV8z3P0Zhr1dBHXrWevS99UsHLqN/z7jUnR9TgPx23N3NP0koZH3eTtykRagLc5qpa/AAzCNNRXA3V2CX4jKSzYldPY1Z81vm9qSgM7XUvO1CYgsbNBWbBcejN8IKHEdQzZ6PIRKbrLAf4FhDld45IjIklR8ibA0VAE1hZesNHMEzd33YaL0X+JIJoCD0cGwpxQXVZYkEKSacArZHPkavXlf4GZHoKsC5IUEvqR9yu48wyG94TengrZIBoosf4MEJb1GzQiXYvuVwh453l/xL1tKIXlxKhHiIL5sb8eaa6OCb7dpV8ZBQ/EtPcj3tN2bsSz9tpVgDNyWnVhH70hBSaeAhb8ssLq059Y44LdX7OCVKXHuSrmEVWQuAohKRSEeO8/Gq/sUAGwA48JEU5+KjIMYqy08FrK5Rs87qU/EevClSu7hZJ3vtBmMgVo3Vh6xd1355iK2pD2yckenqf2cL5hLMWkhwqYj7i9lV1LB2g9+JKCrLum4/hIWfclv/t1Vzw9kKX8CQFb4GoLdmabdt60IRklPGGx98sQJ8A2u7RUYg0lVoWojO+yWwc=

matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8-dev"
    - python: "nightly"
    - python: "pypy2.7-6.0"
    - python: "pypy3.5-6.0"

  # There's a Pipenv issue that currently prevents telnyx-python from building
  # properly on Pypy3:
  #
  #     https://github.com/pypa/pipenv/pull/3322
  #
  # Olivier from Stripe patched it, but we're still waiting on the Pipenv
  # project for a new release (>2018.11.26). When that happens, we can remove
  # pypy3 from this section.
  allow_failures:
    - python: "pypy3.5-6.0"
    - python: "3.4"      # not officially supported, but may as well check
    - python: "3.8-dev"  # not supported until released
    - python: "nightly"  # "may or may not, there is a try"

cache:
  directories:
    - telnyx-mock
  pip: false

env:
  global:
    # If changing this number, please also change it in `tests/conftest.py`.
    - TELNYX_MOCK_VERSION=0.4.0

before_install:
  # Unpack and start telnyx-mock so that the test suite can talk to it
  - |
    if [ ! -d "telnyx-mock/${TELNYX_MOCK_VERSION}" ]; then
      mkdir -p telnyx-mock/${TELNYX_MOCK_VERSION}
      curl -L "https://github.com/team-telnyx/telnyx-mock/releases/download/v${TELNYX_MOCK_VERSION}/telnyx-mock_${TELNYX_MOCK_VERSION}_linux_amd64.tar.gz" -o "telnyx-mock/${TELNYX_MOCK_VERSION}_linux_amd64.tar.gz"
      tar -zxf "telnyx-mock/${TELNYX_MOCK_VERSION}_linux_amd64.tar.gz" -C "telnyx-mock/${TELNYX_MOCK_VERSION}/"
    fi
  - |
    telnyx-mock/${TELNYX_MOCK_VERSION}/telnyx-mock > /dev/null &
    TELNYX_MOCK_PID=$!
  - export PATH="${PATH}:${PWD}/telnyx-mock/${TELNYX_MOCK_VERSION}"

install:
  - make init

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then make lint; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then make fmtcheck; fi
  - make ci

after_success:
  make coveralls
